version: '3'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2255:22"
    volumes:
      # - /Volumes/Backup:/mnt/backup
      - .ssh/authorized_keys:/root/.ssh/authorized_keys
